---
title: "Candy Example"
author: "Molly Caldwell"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    css: style.css
    theme: united
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    number_sections: false
    code_folding: hide
    code_download: true
runtime: shiny
---

```{r setup, include = FALSE}
#set base chunk options (applied to every chunk unless otherwise specified)
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE)

#set working directory
knitr::opts_knit$set(root.dir = "C:/Users/molly/OneDrive - University of Wyoming/Documents/UWyo/Workshops_seminars/RMarkdown/Merkle Lab 10.2022/")
```

```{r Load libraries}
#load libraries
library(DT) #for first interactive table
library(tidyverse)
library(sjPlot) #for linear regression table
library(shiny) #for interactive plot/table at end

library(shinydashboard)
library(maps)
library(dplyr)
library(leaflet)
library(shinycssloaders)
library(shinythemes)
#library(datadigest)
library(rio)
library(stargazer)
```

```{r, include = FALSE}
#Run candy data prep source script
source("candy_data_prep.R", local = knitr::knit_global())
```


# Candy votes {-}

::: {#Table1}
A table example:
:::

```{r}
DT::datatable(candy, options = list(pageLength = 10))
```

# Analysis {-}

## Interactive modeling {-}

```{r}
dashboardPage(
  dashboardHeader(title = "Machine Learning", dropdownMenuOutput("msgOutput")),
  dashboardSidebar(
    sliderInput(
      "Slider1",
      label = h3("Train/Test Split %"),
      min = 0,
      max = 100,
      value = 75
    ),
    textOutput("cntTrain"),
    textOutput("cntTest"),
    br()
    
    #
    # menuItem(
    #   "Generate Report",
    #   tabName = "sectors",
    #   icon = icon("download"),
    #   radioButtons(
    #     'format',
    #     'Document format',
    #     c('HTML', 'Word'),
    #     inline = FALSE,
    #     selected = 1
    #   ),
    #   downloadButton("report", "Download Report", class = "butt"),
    #   tags$head(tags$style(".butt{color: blue !important;}"))
    # )
    
  ),
  dashboardBody(
    fluidPage(
    box(
      selectInput(
        "SelectX",
        label = "Select variables:",
        choices = names(candy),
        multiple = TRUE,
        selected = names(candy)
      ),
      solidHeader = TRUE,
      width = "3",
      status = "primary",
      title = "X variable"
    ),
    box(
      selectInput("SelectY", label = "Select variable to predict:", choices = names(candy)),
      solidHeader = TRUE,
      width = "3",
      status = "primary",
      title = "Y variable"
    )
    
    
    
  ),
  
  fluidPage(  
    
      tabBox(
      id = "tabset1",
      height = "1000px",
      width = 12,
     
      tabPanel("Data",
               box(withSpinner(DTOutput(
                 "Data"
               )), width = 12)),
      tabPanel(
        "Data Summary",
        box(withSpinner(verbatimTextOutput("Summ")), width = 6),
        box(withSpinner(verbatimTextOutput("Summ_old")), width = 6)
      ),
      
      # 
      # tabPanel("Data Strucure",
      #          # box(
      #          #   withSpinner(verbatimTextOutput("structure")), width = "100%"
      #          # ),
      #          explorerOutput("digest")
      #          ),
      tabPanel("Plots",
               box(withSpinner(plotOutput(
                 "Corr"
               )), width = 12)),
      #box(withSpinner(verbatimTextOutput("CorrMatrix")), width = 12),
      tabPanel(
        "Model",
        box(
          withSpinner(verbatimTextOutput("Model")),
          width = 6,
          title = "Model Summary"
        ),
        # box(
        #   withSpinner(verbatimTextOutput("Model_new")),
        #   width = 6,
        #   title = "Model Summary"
        # ),
        # 
        box(
          withSpinner(verbatimTextOutput("ImpVar")),
          width = 5,
          title = "Variable Importance"
        )
      ),
      #textOutput("correlation_accuracy"),
      tabPanel(
        "Prediction",
        box(withSpinner(plotOutput("Prediction")), width = 6, title = "Best Fit Line"),
        box(withSpinner(plotOutput("residualPlots")), width = 6, title = "Diagnostic Plots")
      )
    )
  )
  )
)
```




